[tool.poetry]
name = "pylabs"
version = "0.1.0"
description = ""
authors = ["Parth Thakkar <parth.techblogs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "*"
fastapi = "^0.114.1"
requests = "^2.32.3"
numpy = "^2.2.6"
scikit-learn = "^1.6.1"
pandas = "^2.2.3"
jupyter = "^1.1.1"
pip = "^25.1.1"
langgraph = "^1.0.5"
langchain = "^1.2.0"
langchain-openai = "^1.1.6"
mcp = "^1.25.0"

[tools.poetry]
packages = [{include = "*", from="src"}]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
start = "uvicorn timeserver:app --host 0.0.0.0 --port 8000 --reload"
run = "__main__:main"
